### ISSUE TITLE
Fix release with changeset and deploy to vercel issues

### ISSUE THREAD

**Issue by irrationnelle** [daangn/karrotframe#121]
## release issue

We could watch this log below after release action.

I have tried to reinstall or to update node v16 or to switch `changeset/action` instead of current action by @cometkim.
But I have confirmed that the issue would be from an internal environment that should be fixed.

```
Run changesets/action@v1
[7](https://github.com/daangn/karrotframe/runs/5210438945?check_suite_focus=true#step:5:7)
setting git user
[8](https://github.com/daangn/karrotframe/runs/5210438945?check_suite_focus=true#step:5:8)
/usr/bin/git config user.name "github-actions[bot]"
[9](https://github.com/daangn/karrotframe/runs/5210438945?check_suite_focus=true#step:5:9)
/usr/bin/git config user.email "github-actions[bot]@users.noreply.github.com"
[10](https://github.com/daangn/karrotframe/runs/5210438945?check_suite_focus=true#step:5:10)
setting GitHub credentials
[11](https://github.com/daangn/karrotframe/runs/5210438945?check_suite_focus=true#step:5:11)

[12](https://github.com/daangn/karrotframe/runs/5210438945?check_suite_focus=true#step:5:12)

[13](https://github.com/daangn/karrotframe/runs/5210438945?check_suite_focus=true#step:5:13)

[14](https://github.com/daangn/karrotframe/runs/5210438945?check_suite_focus=true#step:5:14)
/usr/bin/git checkout changeset-release/main
[15](https://github.com/daangn/karrotframe/runs/5210438945?check_suite_focus=true#step:5:15)
Switched to a new branch 'changeset-release/main'
[16](https://github.com/daangn/karrotframe/runs/5210438945?check_suite_focus=true#step:5:16)
branch 'changeset-release/main' set up to track 'origin/changeset-release/main'.
[17](https://github.com/daangn/karrotframe/runs/5210438945?check_suite_focus=true#step:5:17)
/usr/bin/git reset --hard e0dd7486876375f3507adfc09[18](https://github.com/daangn/karrotframe/runs/5210438945?check_suite_focus=true#step:5:18)a58a45291341d
18
HEAD is now at e0dd748 chore: Reinstall @changesets/cli (#118)
[19](https://github.com/daangn/karrotframe/runs/5210438945?check_suite_focus=true#step:5:19)
Error: Have you forgotten to install `@changesets/cli` in "/home/runner/work/karrotframe/karrotframe"?
[20](https://github.com/daangn/karrotframe/runs/5210438945?check_suite_focus=true#step:5:20)
    at b (/home/runner/work/_actions/changesets/action/v1/dist/index.js:1162:2952)
[21](https://github.com/daangn/karrotframe/runs/5210438945?check_suite_focus=true#step:5:21)
    at Object.m [as runVersion] (/home/runner/work/_actions/changesets/action/v1/dist/index.js:1162:3537)
[22](https://github.com/daangn/karrotframe/runs/5210438945?check_suite_focus=true#step:5:22)
    at async /home/runner/work/_actions/changesets/action/v1/dist/index.js:1164:2268
[23](https://github.com/daangn/karrotframe/runs/5210438945?check_suite_focus=true#step:5:23)
Error: Have you forgotten to install `@changesets/cli` in "/home/runner/work/karrotframe/karrotframe"?
```

## vercel issue

To prepare e2e test, a deploy proccess to Vercel should be fixed.

**Comment by irrationnelle** [comment]
I published new `@karrotframe/navigator` and @`karrotframe/plugin` package manually once.

**Comment by cometkim** [comment]
This is not relevant to my action

see https://github.com/changesets/action#with-yarn-2--plugnplay
